### PR TITLE
Dictionaries/en_US

### LINKED ISSUE #8: Spellchecker locale isn't common American English
The dictionary seems to be British English.  Spelling "color" would be flagged as "colour" instead.

### PR DESCRIPTION
**Pull request by mmaietta**
Adding frequency dictionary for en_US.
Added factory in C# for generating new dictionaries. You can optionally provide a file for the dictionary factory for filtering out various words when creating a dictionary.

Fixes #8

### CODE REVIEW

**Comment by justinwilaby** [comment]
@mmaietta - Go ahead and replace the dictionary in the `src/js/__tests__/` directory with this one and run `npm test` to make sure they pass with the new dictionary.

**Comment by justinwilaby** [comment]
...and thank you for the contribution!

**Comment by mmaietta** [comment]
@justinwilaby, I had some fun to support testing for multiple regions as occurrences and common misspellings naturally vary per language region.  Now the same tests run for every region provided in the `language_tests_map.json`

I also removed the txt files in the tests folder so that the tests directly use the files extracted (post npm install) from each .gz. Lemme know your thoughts or any additional improvements I can make.

**Comment by justinwilaby** [comment]
@mmaietta - This makes a very good addition! 

It looks like one of the unit tests is failing due to a missing test file.  Once this is corrected, I think we're good to merge this one.

**Comment by mmaietta** [comment]
🎉 
Could you please deploy a new npm version? I'd love to be able to use the en_US locally :)

**Comment by justinwilaby** [comment]
@mmaietta - All set. 0.3.0 published with your changes! Thanks again.

**Pull request merged**
